### ISSUE TITLE
Permissions/ownership update on File objects

### ISSUE THREAD

**Issue by jtfrey** [warewulf/warewulf3#78]
What was the reason for the File `sync()` function only updating the checksum and size?  Why are ownerships and privileges not updated to match the origin file?  If I modify either of those attributes on the origin file, I must remove the file object (and silently have provisioning references to it removed, too) then re-add it, then re-add it to any provisioning profiles on which it had been present.

FWIW, the `sync()` code also doesn't check to ensure that the file type from the datastore still matches the type of the origin file.  It blindly assumes that to be the case and proceeds with opening and reading the file, etc.

**Comment by jmstover** [comment]
Well, at least in our setup, that would break things horribly. We'll get multiple VNFS's that use the same files. But, because it wasn't watched when creating the VNFS, UID's will be all off.

Soooo.... we create multiple files that use the same ORIGIN (as the same file is needed), and just have different `--uid`, `--gid`, and/or `--mode` flags (`wwsh file` command) as needed. 

>  If I modify either of those attributes

Use `wwsh file` ... for example:

  `wwsh file set [Name] --uid=1234 --gid=4321 --mode=0660`

> the `sync()` code also doesn't check to ensure that the file type from 
> the datastore still matches the type of the origin file

Err... why would it? It's a different file at that point. IMO, trying to protect for every eventuality that _could_ happen, is just going to cause a headache. There's way to many of them. It sets on import, and trusts the admin to not do something... strange.

**Comment by jtfrey** [comment]
> Soooo.... we create multiple files that use the same ORIGIN (as the same file is needed), and just have different --uid, --gid, and/or --mode flags (wwsh file command) as needed.

Okay, that was a use case I hadn't considered.  But perhaps there's a way we could augment the existing functionality to make this more straightforward for locales which implement universal uid/gid (including one-off clusters)?

- If `--uid`, `--gid`, or `--mode` options are specified without an accompanying value, `stat()` the origin entity and use its current value for that option.
- Alter the `sync` subcommand to accept the `--uid`, `--gid`, and `--mode` flags (behaving the same way as above) to enable full sync'ing of the file object (content + meta data) against the origin entity. 

> Err... why would it? It's a different file at that point. IMO, trying to protect for every eventuality that could happen, is just going to cause a headache. There's way to many of them. It sets on import, and trusts the admin to not do something... strange.

So it seems that as far as file objects go, once the origin entity has been imported into the datastore the file object represents a unique entity which is NOT strongly associated with the origin entity.  The _sync_ command is a convenience only, and does not imply such any such association between them.  But I would say that is an argument **for** having such sanity checks on the `sync()` function:  if the assumption is that the origin and file object are unique and distinct, then at the least the file type should be verified before sync'ing into the datastore.  I don't see that check as being prohibitively difficult to implement.

**Comment by bensallen** [comment]
> Alter the sync subcommand to accept the --uid, --gid, and --mode flags (behaving the same way as above) to enable full sync'ing of the file object (content + meta data) against the origin entity.

This seems like a reasonable approach, if someone wants to take this on.

**Comment by holmanbph** [comment]
I'm new to warewulf (and fairly new to perl as well),  but I'd be happy to give this a shot.

**Comment by jmstover** [comment]
@holmanbph 
Hi Brett,

  If you want to have a go at this you'll want to look around `common/lib/Warewulf/File.pm` at the `sync()` routine. Right now the only thing that's doing with relation to the file, is grabbing the `$binstore` for the file object id, and replacing the contents with what's contained from the file on disk.

  I _think_ in the `sync()` routine you can use:  `$self->uid()` / `$self->gid()` / etc... to compare against the information from `@statinfo`. 

  From a quick glance at it that's what I can give you to start out with. Holler if you have any more questions about anything if you want to take a shot at it.

Thanks,
-J

**Comment by jtfrey** [comment]
I've been looking at this one for a while, and full implementation is not exactly simple.

1. Changes to sync() must account for the origin() being a single filesystem object versus a piped command or an array of entities.  The action is only applicable when the origin() is a single filesystem object.
2. Should modifications to metadata inside sync() be gated by a summary and yes/no user interaction, as in the "set" subcommand?
3. The simplest change to the Warewulf/Modules/Cli/File.pm optargs is to make the argument to the -m/-u/-g optional, e.g. 'm|mode:s' then test for defined($opt_mode) (indicating the option was used) and an empty string in $opt_mode implies the value should be taken from the origin().  But then other commands that use those flags — and expect argument to be mandatory — need to be modified to account for an empty string in $opt_mode.

My own work has covered (1); (2) is a question needing a consensus; and (3) requires the introduction of the same logic from (1) into the set_file_member() method.

**Comment by jmstover** [comment]
> or array of entities

`sync()` is on a single file object. `$self` in the `sync()` function is the current file object being worked on.

What the CLI does for `wwsh file sync` is take the `$objSet` (*every* file object if empty) and *foreach* value in `$objSet`, it runs: `$obj->sync()`.  (`common/lib/Warewulf/Module/Cli/File.pm` ~line 477)

> Should modifications to metadata inside sync() be gated by a summary and yes/no user interaction

No. `sync()` is an internal call. It just does what it needs to. The summary comes from the CLI handling.

Would this work better if we added a `--overwrite` option to change the behavior? So you would do:

`wwsh file --overwrite sync [file obj]`

And it would then basically do a *import* of the file which sets the UID/GID/etc... based on what's on the file. Instead of changing the behavior?

**Comment by jtfrey** [comment]
> sync() is on a single file object. $self in the sync() function is the current file object being worked on.
> 
> What the CLI does for wwsh file sync is take the $objSet (every file object if empty) and foreach value in $objSet, it runs: $obj->sync(). (common/lib/Warewulf/Module/Cli/File.pm ~line 477)

Yes -- but a File object's origin() can be a piped command, a path, or an arbitrary array of the other two.  The data committed to the datastore on sync() is then a concatenation of all of them.  E.g. I can do this:

```
# wwsh file new --origin=/etc/passwd.base --origin=/etc/passwd.ldap --path=/etc/passwd --mode=0644 test-concat
About to apply 2 action(s) to 1 file(s):

     SET: MODE                 = 0664
     SET: ORIGIN               = /etc/passwd.base,/etc/passwd.ldap

Proceed?
Yes/No [no]> Yes
# wwsh file sync test-concat
# wwsh file print test-concat
#### test-concat ##############################################################
test-concat     : ID               = 44
test-concat     : NAME             = test-concat
test-concat     : PATH             = /etc/passwd
test-concat     : ORIGIN           = /etc/passwd.base,/etc/passwd.ldap
test-concat     : FORMAT           = UNDEF
test-concat     : CHECKSUM         = 90ad1004831c9dc74041632f33557b1e
test-concat     : INTERPRETER      = UNDEF
test-concat     : SIZE             = 4402
test-concat     : MODE             = 0644
test-concat     : UID              = 0
test-concat     : GID              = 0
```

and Warewulf happily fills the datastore with the contents of those two files in that sequence.  So attempting to pull mode/uid/gid on sync() for this file object doesn't compute.

> > Should modifications to metadata inside sync() be gated by a summary and yes/no user interaction
>
> No. sync() is an internal call. It just does what it needs to. The summary comes from the CLI handling.

My bad, when I said sync() I meant the code in the Cli module that handles the "file sync" subcommand.  So the question is really "should metadata updates in 'file sync' be summarized and persistence gated via yes/no."  In the implementation I'm working on right now, the answer is "yes" to remain consistent with the "file set" subcommand behavior.

**Comment by jmstover** [comment]
Sync and Set are different commands though.

`sync()` says:  "Read the contents from this file on disk for the datastore object whos contents are at `ORIGIN`"
`wwsh file set` says: "Don't care what the ORIGIN file says, make the File object settings this."

> "should metadata updates in 'file sync' be summarized and persistence gated via yes/no."

How are you determining there are differences in the CLI? In the loop are you looking at each `$obj->uid()` / `$obj->gid()` finding the origin files `$obj->origin()` and comparing them the `lstat()`/`stat()`? What takes preference, what's on the ORIGIN file or what's on the object? I would want the file **object** to have preference, not ORIGIN as per my use case.

Someone always does:  `wwsh file sync` to sync changes to a _single_ file (there were a few hundred files, symlink's as files, etc... yeah we abused what can be done with the file object ;) )... and that would destroy my use case where we have the same `ORIGIN` but different `--uid`/`--gid` settings if `ORIGIN` wins on a pure `sync`.

So... are you trying to do something like:

`wwsh file sync --uid=-1 [file obj]`

So, when the file is sync'd, the `UID` settings from the `ORIGIN` file are passed along? Again, if that's what you're wanting, why not a `--overwrite` option that when set, instead of doing a **sync** does a **import** ... since that's really what you're wanting. A clean re-write of everything from the file on disk to the file object.

We can't make it be empty. The parsing for the `--uid` flag comes from the `file` command ... so it **needs** to accept a digit.... `file import` is doing:

`$obj->uid((defined($opt_uid)) : ($opt_uid) ? ($uid));`

To set the values with either what is passed on the command line or the value of `ORIGIN` on **import**. On `file set` ... it's calling `set_file_member()` to set the corresponding key.

What behavior are you trying to duplicate? What `file import` does? What `file set` does?

**Comment by holmanbph** [comment]
> Changes to sync() must account for the origin() being a single filesystem object versus a piped command or an array of entities. The action is only applicable when the origin() is a single filesystem object.

@jtfrey  So your implementation will only sync the uid/gid/mode metadata if the origin is a single file in the filesystem?  I guess that simplifies handling the use case you've presented, but it may be a bit confusing to users when sync() *sometimes* updates metadata and *sometimes* doesn't.  Also, making persistence "gated by a yes/no" changes existing behavior to how the sync command is currently handled in the CLI.  

Perhaps using `wwsh file --overwrite sync [file obj]` as suggested by @jmstover  to update `gid`/`uid`/`mode` metadata when you wish this to happen, and print out a message indicating that `metadata was not modified` when `ORIGIN` is referring to multiple files to avoid confusion by the user?  I think this option might fit both use cases presented by @jmstover and @jtfrey.  Then you could use set() any time you need to have a file with multiple `ORIGIN`'s "synced".

**Comment by jmstover** [comment]
PR #112 was merged in that adds a `--overwrite` flag... i.e.  `wwsh file --overwrite sync [fname]`
